AllCops:
  Exclude:
      - 'db/**/*'
      - 'bin/**/*'
      - 'Gemfile'
      - 'spec/**/*'
      - 'config/**/*'

  DisplayStyleGuide: true

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false